language: generic
sudo: required
dist: trusty
git:
    depth: 200
services:
    - docker
branches:
    only:
        - master
cache:
    directories:
        - ~/bin
        - ~/opt

before_install:
    # See https://github.com/travis-ci/travis-ci/issues/7940
    - if [ "push" = "$TRAVIS_EVENT_TYPE" ] && [ "master" = "$TRAVIS_BRANCH" ]; then
          export GCP_PROJECT_NAME=$PROD_GCP_PROJECT_NAME;
          export GCP_SERVICE_ACCOUNT_KEY=$PROD_GCP_SERVICE_ACCOUNT_KEY;
      fi
    - curl ci-utils.bwcom.io/gcloud/install | bash
    - curl ci-utils.bwcom.io/gcloud/auth | bash
    - curl ci-utils.bwcom.io/slipstream/install | bash
    - export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/tmp/gcp-service-account-key.json

script:
    - set -e
    - docker build -t k8smap .
    - $TRAVIS_BUILD_DIR/bin/docker-publish.sh
