language: generic
sudo: required
dist: trusty
git:
    depth: 200
services:
    - docker
branches:
    only:
        - master
cache:
    directories:
        - ~/bin
        - ~/opt

before_install:
    # See https://github.com/travis-ci/travis-ci/issues/7940
    - curl ci-utils.bwcom.io/gcloud/install | bash
    - curl ci-utils.bwcom.io/gcloud/auth | bash
    - curl ci-utils.bwcom.io/slipstream/install | bash
    - export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/tmp/gcp-service-account-key.json
    - export GIT_DESCRIBE=$(git describe --all --tags)

script:
    - set -e
    - docker build -t eu.gcr.io/$GCP_PROJECT_NAME/k8smap:$GIT_DESCRIBE .
    - $TRAVIS_BUILD_DIR/bin/docker-publish.sh
