# WARNING: do not publish this image since it contains
# a config file that has tokens in it!

FROM node:9.11.1-alpine as k8smap-build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM nginx:1.13.12-alpine as k8smap-production-stage
COPY --from=k8smap-build-stage /app/dist /usr/share/nginx/html

# sites-enabled is not included in images nginx.conf for some reason
COPY conf/tmp/nginx.conf.prod /etc/nginx/conf.d/k8smap.conf

# this config conflicts with k8smap config
RUN rm /etc/nginx/conf.d/default.conf

# template nginx config out..

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
