apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8smap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8smap
    spec:
      volumes:
        - name: k8s-conf
          secret:
            secretName: k8s-conf
      containers:
        - name: k8smap
          image: roobert/k8smap-vue
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: k8s-conf
              readOnly: true
              mountPath: /usr/share/nginx/html/
              subPath: config.vue.json
            - name: k8s-conf
              readOnly: true
              mountPath: /etc/nginx/conf.d/
              subPath: k8smap.conf
