apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8smap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8smap
    spec:
      volumes:
        - name: k8s-conf
          secret:
            secretName: k8s-conf
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: config.vue.json
                path: config.vue.json
      containers:
        - name: k8smap
          image: roobert/k8smap-vue
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: k8s-conf
              mountPath: /usr/share/nginx/html/config.vue.json
              subPath: config.vue.json
            - name: k8s-conf
              mountPath: /etc/nginx/conf.d/k8smap.conf
              subPath: nginx.conf
